# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build server artifact

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build uber-jar
        run: mvn -B package --file javaServer/score-hunter-server/pom.xml
      - name: Archive uber-jar
          uses: actions/upload-artifact@v2
          with:
            name: JarResult
            path: javaServer/score-hunter-server/target/*-runner.jar
      - name: Build native executable
        run: mvn -B clean package --file javaServer/score-hunter-server/pom.xml -Pnative -Dquarkus.native.container-build=true
      - name: Archive Native Build
        uses: actions/upload-artifact@v2
        with:
          name: NativeResult
          path: javaServer/score-hunter-server/target/*-runner
